spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#Fake-SMTP-Server(Runs on jdk: 1.8): https://nilhcem.com/FakeSMTP/
  mail:
    host: 127.0.0.1
    port: 25
  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  secret:
    key: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347999"
  expiry: 1800000

admin:
  name: "aayush"
  password: "aayush"
  email: "caayush96@gmail.com"
  role: "ROLE_ADMIN"
  phone: "9844430402"

thread:
  corePoolSize: 10
  maxPoolSize: 10
  queueCapacity: 100
  threadNamePrefix: "Save-Multiple-Users-thread-pool-"

flags:
  sendEmail: true

emailLogChar:
  maxLength: 255


