spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: ${external.database.username}
    password: ${external.database.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#Fake-SMTP-Server(Runs on jdk: 1.8): https://nilhcem.com/FakeSMTP/
  mail:
    host: 127.0.0.1
    port: 25
  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  secret:
    key: ${external.jwt.key}
  expiry: 1800000

admin:
  name: ${external.admin.name}
  password: ${external.admin.password}
  email: "caayush96@gmail.com"
  role: "ROLE_ADMIN"
  phone: "9844430402"

thread:
  corePoolSize: 10
  maxPoolSize: 10
  queueCapacity: 100
  threadNamePrefix: "Save-Multiple-Users-thread-pool-"

flags:
  sendEmail: true

emailLogChar:
  maxLength: 255

external:
  property:
    file:
#      path: file:/C:/Users/ThinkPad/Documents/Property_File/external_application.properties
      path: file:/C:/Users/ThinkPad/Documents/Property_File/encryption/src/main/resources/external_application.properties
    encryption:
      key: ${ENCRYPTION_KEY}


